---
  - name: Create Local Account
    hosts: all
    gather_facts: yes
    vars:
       ansible_svc_account: "{{ account }}"
       ansible_home_directory: "{{ home_directory }}"
       account_sudoers: "{{ account_sudoer }}"
       user_comment: "{{ user_comment }}"
       public_key: "{{ public_key }}"

    tasks:
       
    - name: Creating the "{{ account }}" user account and the "{{ home_directory }}/{{ account }}" home directory
      ansible.builtin.user:
        name: "{{ account }}"
        home: "{{ home_directory }}/{{ account }}"
        create_home: true
        comment: "{{ user_comment }}"
        password: "{{ password }}"
        state: present
        remove: false
        system: true
 
    - name: "{{ account }} is included in sudoers.d directory"
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ account }}"
        content: "{{ account }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: 'ug+rwX,o='
      when: account_sudoer == 'true'
      
    - name: Making sure the public key for the "{{ account }}" account is present
      ansible.posix.authorized_key:
        user: "{{ account }}"
        state: present
        key: "{{ public_key }}"
      when: public_key != 'false'