---
- name: Create the Ansible service account on target hosts
  hosts: all
  gather_facts: True
  tasks:
    - name: service account is present
      user:
        name: "ansible"
        home: "/home/ansible"
        comment: Service account for Ansible
        state: present
        system: True
