---
- name: Create the Ansible service account on target hosts
  hosts: all
  gather_facts: True
  tasks:
    - name: service account is present
      user:
        name: "{{svcansible_username}}"
        home: "{{svcansible_home}}/{{svcansible_username}}"
        comment: Service account for Ansible
        state: present
        system: True
