---
- name: Create the Ansible service account on target hosts
  hosts: all
  gather_facts: True
  ansible_svc_account: ''
  
  tasks:
    - name: service account is present
      user:
        name: '((ansible_svc_account}}'
        home: "/home/'((ansible_svc_account}}'"
        comment: Service account for Ansible
        state: present
        system: True
