---
- name: Create the Ansible service account on target hosts
  hosts: all
  gather_facts: True
  
- name: include vars/myvariables.yml
      ansible.builtin.include_vars:
        file: ./vars/myvariables.yml
      tags: always
  
  tasks:
    - name: service account is present
      user:
        name: '(( ansible_svc_account }}'
        home: "/home/'(( ansible_svc_account }}'"
        comment: Service account for Ansible
        state: present
        system: True
