---
  - name: foobar
    hosts: localhost
    
    tasks:
  
    - name: hello i am here
      ansible.builtin.set_fact: 
        create_date: "{{ ansible_date_time.date }}"
    
    - name: WTF
      ansible.builtin.debug: 
        var: create_date

    - name: overhere
      ansible.builtin.set_fact: 
        vpc_create_time: "{{ ansible_date_time.time }}"
    
    - name: Time
      ansible.builtin.debug: 
        var: vpc_create_time