---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ esxiname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ servername }}"
      template: "{{ templatename }}"
      #datacenter: DC1
      folder: /DC1/vm
      state: poweredon
      wait_for_ip_address: yes
