---
- name: Files that I want deployed to make my life better
  hosts: all
  gather_facts: True

  tasks:

- name: Template file that will give me sudo access with no passwd
  ansible.builtin.template:
    src: /AnsibleAutomationPlatform/files/sudoers_d/eames
    dest: /etc/sudoers.d/eames
    owner: root
    group: root
    mode: '0600'
