---
- name: Getting ready to install Red Hat Insights
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
  
  - name: Making sure the Insights Client is installed.
    ansible.builtin.yum:
      name: 
        - insights-client
      state: present
  
  - name: Registering the system with Red Hat Insights
    ansible.builtin.command: insights-client --register
