---
- name: Configuring the prelogin message
    hosts: all
    gather_facts: no
    
  tasks:
  
  - name: Copy the sshd-banner file into place
    copy:
      src: files_to_deploy/sshd-banner
      dest: /etc/ssh/sshd-banner
      owner: root
      group: root
      mode: u+rw,g-wx,o-wx
