---
- name: Registering system with Red Hat
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    username: "{{ username }}"
    password: "{{ password }}"
    
  tasks:
  
  - name: Register and subscribe the system 
    redhat_subscription:
      username: "{{ username }}"
      password: "{{ password }}"
      state: present
